name: 🐞 Bug Report
description: Report an issue with STDF
title: '[Bug]: '
labels: ['bug']
body:
    - type: markdown
      attributes:
          value: |
              Thank you for taking the time to fill out this bug report! If you have a usage question or are unsure if it's really a bug, please make sure:

              - You are using the latest version of the code.
              - You have checked the open and closed issues to see if your issue has already been reported.
              - If there is a similar issue in the issues list, please provide additional information in the corresponding issue.
              - Your description of the problem is concise and clear, not just from your own perspective.

    - type: dropdown
      id: module
      attributes:
          label: Module
          description: Which module does this bug belong to?
          options:
              - stdf (STDF component)
              - create (create-stdf scaffolding)
              - vscode (STDF VS Code plugin)
              - icon (rollup-plugin-stdf-icon plugin)
              - md (rollup-plugin-md-ts plugin)
              - demo (STDF demo)
              - doc (STDF site and documentation)
              - other (other)
      validations:
          required: true

    - type: input
      id: version
      attributes:
          label: Version
          description: If it is stdf/create/icon/vscode/md, please indicate the version in which this bug occurred.
      validations:
          required: false

    - type: textarea
      id: bug-description
      attributes:
          label: Bug Description
          description: Please describe the bug clearly and concisely.
          placeholder: When...
      validations:
          required: true

    - type: textarea
      id: reproduction
      attributes:
          label: Reproduction
          description: You can use text/images/short videos to explain how to reproduce the issue, but please provide a series of information about the environment where the problem occurs, such as device model and version, operating system and version, browser, etc. You can also use [StackBlitz](https://stackblitz.com) or [CodePen](https://codepen.io) or other online IDEs to quickly create a project to demonstrate the bug. In short, make it easy for others to understand how to reproduce the bug.
          placeholder: On iPhone 13 Pro with iOS 16...
      validations:
          required: true

    - type: textarea
      id: idea
      attributes:
          label: Your Idea
          description: If you have a solution or idea for this bug, you can describe it here.
          placeholder: I think...
      validations:
          required: false
