name: 🐞 缺陷报告
description: 报告 STDF 问题
title: '[Bug]: '
labels: ['bug']
body:
    - type: markdown
      attributes:
          value: |
              感谢您抽出时间填写这份错误报告！如果您有使用问题，或者不确定是否真的是一个错误，请确保：

              - 你使用的是最新版代码。
              - 你已经查看过开启与关闭状态的 issues ，其中并没有你发现的此问题。
              - 如果 issues 中已有相同问题，你需要补充，请尽量在对应的 issue 中补充讨论。
              - 你对问题的表述简洁清晰，不只在你的情景角度能理解。

    - type: dropdown
      id: module
      attributes:
          label: 模块
          description: 此缺陷属于哪个模块？
          options:
              - stdf (STDF 组件)
              - create (create-stdf 脚手架)
              - vscode (STDF VS Code 插件)
              - icon (rollup-plugin-stdf-icon 插件)
              - md (rollup-plugin-md-ts 插件)
              - demo (STDF demo)
              - doc (STDF 站点与文档)
              - other (其他)
      validations:
          required: true

    - type: input
      id: version
      attributes:
          label: 版本
          description: 如果是选择的是 stdf、create、icon、vscode、md，请注明此缺陷出现的版本。
      validations:
          required: false

    - type: textarea
      id: bug-description
      attributes:
          label: 描述缺陷
          description: 请清晰简明地描述清楚该缺陷内容。
          placeholder: 当...
      validations:
          required: true

    - type: textarea
      id: reproduction
      attributes:
          label: 复现
          description: 你可以使用文字/图片/简短视频说清楚如何复现此问题，但请尽量说清设备型号与版本、操作系统与版本、浏览器等一系列出现问题的环境。也可以使用 [StackBlitz](https://stackblitz.com) 或者 [CodePen](https://codepen.io) 或其他在线 IDE 快速创建一个工程展示此缺陷。总之让别人能快速明白此缺陷的复现情况。
          placeholder: 在 iPhone 13 Pro 的 iOS 16...
      validations:
          required: true

    - type: textarea
      id: idea
      attributes:
          label: 你的想法
          description: 如果你对该缺陷有解决方案或思路，可以在这里描述。
          placeholder: 我认为...
      validations:
          required: false
