// 英语 english
export const en_US = {
	sort: 0,
	name: 'English',
	hnay: 'Has not adapted yet',
	pn: 'Please enter the project name',
	pncbne: 'Project name cannot be empty',
	pane: 'Project name already exists',
	psat: 'Please select a template',
	oc: 'Operation cancelled',
	pca: 'Please choose again',
	psai: 'Please select icon usage',
	pm: 'Please select package manager',
	cfsing: 'Creating file...',
	pcsucc: 'Project created successfully!',
	tgs: 'To get started:',
	pcyt_vt: 'Tip: please configure Initial Color System in src/app.css, reference https://stdf.design/guide/theme',
	pcyt_vu: 'Tip: please configure Initial Color System in src/app.css, reference https://stdf.design/guide/theme',
	cferror: 'Failed to create file',
	pectn: 'Please enter the correct template name!',
	pic: 'Please enter the correct icon usage!',
};

// 简体中文 chinese
export const zh_CN = {
	sort: 1,
	name: '简体中文',
	hnay: '暂未适配',
	pn: '请输入项目名称',
	pncbne: '项目名称不能为空',
	pane: '项目名称已存在',
	psat: '请选择一个模板',
	oc: '操作已取消',
	pca: '请重新选择',
	psai: '请选择图标使用方式',
	pm: '请选择包管理工具',
	cfsing: '正在创建文件...',
	pcsucc: '项目创建成功!',
	tgs: '开始：',
	pcyt_vt: '提示：请到 src/app.css 配置初始主题色，参考 https://stdf.design/guide/theme',
	pcyt_vu: '提示：请到 src/app.css 配置初始主题色，参考 https://stdf.design/guide/theme',
	cferror: '创建文件失败',
	pectn: '请输入正确的模板名称！',
	pic: '请输入正确的图标使用方式！',
};

// 繁體中文 chinese traditional
export const zh_TW = {
	sort: 2,
	name: '繁體中文',
	hnay: '暫未適配',
	pn: '請輸入項目名稱',
	pncbne: '項目名稱不能為空',
	pane: '項目名稱已存在',
	psat: '請選擇一個模板',
	oc: '操作已取消',
	pca: '請重新選擇',
	psai: '請選擇圖標使用方式',
	pm: '請選擇包管理工具',
	cfsing: '正在創建文件...',
	pcsucc: '項目創建成功!',
	tgs: '開始：',
	pcyt_vt: '提示：請到 src/app.css 配置初始主題色，參考 https://stdf.design/guide/theme',
	pcyt_vu: '提示：請到 src/app.css 配置初始主題色，參考 https://stdf.design/guide/theme',
	cferror: '創建文件失敗',
	pectn: '請輸入正確的模板名稱！',
	pic: '請輸入正確的圖標使用方式！',
};

// 日语 japanese
export const ja_JP = {
	sort: 3,
	name: '日本語',
	hnay: 'まだ適応されていません',
	pn: 'プロジェクト名を入力してください',
	pncbne: 'プロジェクト名は空にできません',
	pane: 'プロジェクト名が既に存在します',
	psat: 'テンプレートを選択してください',
	oc: '操作がキャンセルされました',
	pca: 'もう一度選択してください',
	psai: 'アイコンの使用方法を選択してください',
	pm: 'パッケージマネージャーを選択してください',
	cfsing: 'ファイルを作成しています...',
	pcsucc: 'プロジェクトが正常に作成されました!',
	tgs: '開始：',
	pcyt_vt: 'ヒント：src/app.css ファイルで初期カラーシステムを設定し、参考 https://stdf.design/guide/theme',
	pcyt_vu: 'ヒント：src/app.css ファイルで初期カラーシステムを設定し、参考 https://stdf.design/guide/theme',
	cferror: 'ファイルの作成に失敗しました',
	pectn: '正しいテンプレート名を入力してください！',
	pic: '正しいアイコン使用方法を入力してください！',
};

// 韩语 korean
export const ko_KR = {
	sort: 4,
	name: '한국어',
	hnay: '아직 적응하지 못했습니다',
	pn: '프로젝트 이름을 입력하십시오',
	pncbne: '프로젝트 이름은 비워 둘 수 없습니다',
	pane: '프로젝트 이름이 이미 있습니다',
	psat: '템플릿을 선택하십시오',
	oc: '작업이 취소되었습니다',
	pca: '다시 선택하십시오',
	psai: '아이콘 사용 방법을 선택하십시오',
	pm: '패키지 관리자를 선택하십시오',
	cfsing: '파일을 만드는 중입니다...',
	pcsucc: '프로젝트가 성공적으로 생성되었습니다!',
	tgs: '시작：',
	pcyt_vt: '팁: src/app.css 파일에서 초기 색상 시스템을 구성하고 참조 https://stdf.design/guide/theme',
	pcyt_vu: '팁: src/app.css 파일에서 초기 색상 시스템을 구성하고 참조 https://stdf.design/guide/theme',
	cferror: '파일 생성 실패',
	pectn: '올바른 템플릿 이름을 입력하십시오!',
	pic: '올바른 아이콘 사용 방법을 입력하십시오!',
};

// 西班牙语 spanish
export const es_ES = {
	sort: 5,
	name: 'Español',
	hnay: 'Aún no se ha adaptado',
	pn: 'Por favor ingrese el nombre del proyecto',
	pncbne: 'El nombre del proyecto no puede estar vacío',
	pane: 'El nombre del proyecto ya existe',
	psat: 'Por favor seleccione una plantilla',
	oc: 'Operación cancelada',
	pca: 'Por favor, elija de nuevo',
	psai: 'Por favor seleccione el uso de iconos',
	pm: 'Por favor seleccione un administrador de paquetes',
	cfsing: 'Creando archivo...',
	pcsucc: 'Proyecto creado con éxito!',
	tgs: 'Para empezar:',
	pcyt_vt: 'Consejo: configure su sistema de colores en reference https://stdf.design/guide/theme',
	pcyt_vu: 'Consejo: configure su sistema de colores en reference https://stdf.design/guide/theme',
	cferror: 'Error al crear archivo',
	pectn: '¡Por favor ingrese el nombre de la plantilla correcto!',
	pic: '¡Por favor ingrese el uso correcto de iconos!',
};

// 俄语 russian
export const ru_RU = {
	sort: 6,
	name: 'Русский',
	hnay: 'Еще не адаптировано',
	pn: 'Пожалуйста, введите название проекта',
	pncbne: 'Название проекта не может быть пустым',
	pane: 'Название проекта уже существует',
	psat: 'Пожалуйста, выберите шаблон',
	oc: 'Операция отменена',
	pca: 'Пожалуйста, выберите снова',
	psai: 'Пожалуйста, выберите использование иконок',
	pm: 'Пожалуйста, выберите пакетный менеджер',
	cfsing: 'Создание файла...',
	pcsucc: 'Проект успешно создан!',
	tgs: 'Чтобы начать:',
	pcyt_vt: 'Совет: настройте свой цветовой систему в ссылке https://stdf.design/guide/theme',
	pcyt_vu: 'Совет: настройте свой цветовой систему в ссылке https://stdf.design/guide/theme',
	cferror: 'Не удалось создать файл',
	pectn: 'Пожалуйста, введите правильное название шаблона!',
	pic: 'Пожалуйста, введите правильное использование иконок!',
};

// 法语 french
export const fr_FR = {
	sort: 7,
	name: 'Français',
	hnay: "N'a pas encore adapté",
	pn: 'Veuillez saisir le nom du projet',
	pncbne: 'Le nom du projet ne peut pas être vide',
	pane: 'Le nom du projet existe déjà',
	psat: 'Veuillez sélectionner un modèle',
	oc: 'Opération annulée',
	pca: 'Veuillez choisir à nouveau',
	psai: "Veuillez sélectionner le mode d'utilisation des icônes",
	pm: 'Veuillez sélectionner un gestionnaire de paquets',
	cfsing: 'Création de fichier...',
	pcsucc: 'Projet créé avec succès!',
	tgs: 'Pour commencer:',
	pcyt_vt: 'Conseil: veuillez configurer votre système de couleurs dans reference https://stdf.design/guide/theme',
	pcyt_vu: 'Conseil: veuillez configurer votre système de couleurs dans reference https://stdf.design/guide/theme',
	cferror: 'Échec de la création du fichier',
	pectn: 'Veuillez saisir le nom du modèle correct!',
	pic: "Veuillez saisir le mode d'utilisation correct des icônes!",
};

// 德语 german
export const de_DE = {
	sort: 8,
	name: 'Deutsch',
	hnay: 'Noch nicht angepasst',
	pn: 'Bitte geben Sie den Projektnamen ein',
	pncbne: 'Projektname darf nicht leer sein',
	pane: 'Projektname existiert bereits',
	psat: 'Bitte wählen Sie eine Vorlage aus',
	oc: 'Vorgang abgebrochen',
	pca: 'Bitte wählen Sie erneut',
	psai: 'Bitte wählen Sie die Verwendung von Icons',
	pm: 'Bitte wählen Sie einen Paketmanager aus',
	cfsing: 'Erstelle Datei...',
	pcsucc: 'Projekt erfolgreich erstellt!',
	tgs: 'Um zu beginnen:',
	pcyt_vt: 'Tip: please configure your color system in reference https://stdf.design/guide/theme',
	pcyt_vu: 'Tip: please configure your color system in reference https://stdf.design/guide/theme',
	cferror: 'Fehler beim Erstellen der Datei',
	pectn: 'Bitte geben Sie den richtigen Vorlagennamen ein!',
	pic: 'Bitte geben Sie den richtigen Verwendungsmodus für Icons ein!',
};

// 意大利语 italian
export const it_IT = {
	sort: 9,
	name: 'Italiano',
	hnay: 'Non ancora adattato',
	pn: 'Inserisci il nome del progetto',
	pncbne: 'Il nome del progetto non può essere vuoto',
	pane: 'Il nome del progetto esiste già',
	psat: 'Seleziona un modello',
	oc: 'Operazione annullata',
	pca: 'Seleziona di nuovo',
	psai: 'Seleziona il modo di utilizzo delle icone',
	pm: 'Seleziona un gestore di pacchetti',
	cfsing: 'Creazione del file in corso...',
	pcsucc: 'Progetto creato con successo!',
	tgs: 'Per iniziare:',
	pcyt_vt: 'Consiglio: configura il tuo sistema di colori in https://stdf.design/guide/theme',
	pcyt_vu: 'Consiglio: configura il tuo sistema di colori in https://stdf.design/guide/theme',
	cferror: 'Impossibile creare il file',
	pectn: 'Inserisci il nome del modello corretto!',
	pic: 'Inserisci il modo di utilizzo corretto delle icone!',
};
