import { wrap } from 'svelte-spa-router/wrap';

import Home from './pages/home/Home.svelte';

// import Z from './pages/z/Z.svelte';

export const routes = {
    '/': Home,
    '/button': wrap({ asyncComponent: () => import('./pages/button/ButtonDemo.svelte') }),
    '/icon': wrap({ asyncComponent: () => import('./pages/icon/IconDemo.svelte') }),
    '/navBar': wrap({ asyncComponent: () => import('./pages/navBar/NavBarDemo.svelte') }),
    '/divider': wrap({ asyncComponent: () => import('./pages/divider/DividerDemo.svelte') }),
    '/cell': wrap({ asyncComponent: () => import('./pages/cell/CellDemo.svelte') }),
    '/switch': wrap({ asyncComponent: () => import('./pages/switch/SwitchDemo.svelte') }),
    '/avatar': wrap({ asyncComponent: () => import('./pages/avatar/AvatarDemo.svelte') }),
    '/tabs': wrap({ asyncComponent: () => import('./pages/tabs/TabsDemo.svelte') }),
    '/tabBar': wrap({ asyncComponent: () => import('./pages/tabBar/TabBarDemo.svelte') }),
    '/steps': wrap({ asyncComponent: () => import('./pages/steps/StepsDemo.svelte') }),
    '/indexBar': wrap({ asyncComponent: () => import('./pages/indexBar/IndexBarDemo.svelte') }),
    '/radio': wrap({ asyncComponent: () => import('./pages/radio/RadioDemo.svelte') }),
    '/checkbox': wrap({ asyncComponent: () => import('./pages/checkbox/CheckboxDemo.svelte') }),
    '/input': wrap({ asyncComponent: () => import('./pages/input/InputDemo.svelte') }),
    '/grids': wrap({ asyncComponent: () => import('./pages/grids/GridsDemo.svelte') }),
    '/swiper': wrap({ asyncComponent: () => import('./pages/swiper/SwiperDemo.svelte') }),
    '/placeholder': wrap({ asyncComponent: () => import('./pages/placeholder/PlaceholderDemo.svelte') }),
    '/skeleton': wrap({ asyncComponent: () => import('./pages/skeleton/SkeletonDemo.svelte') }),
    '/rate': wrap({ asyncComponent: () => import('./pages/rate/RateDemo.svelte') }),
    '/slider': wrap({ asyncComponent: () => import('./pages/slider/SliderDemo.svelte') }),
    '/badge': wrap({ asyncComponent: () => import('./pages/badge/BadgeDemo.svelte') }),
    '/noticeBar': wrap({ asyncComponent: () => import('./pages/noticeBar/NoticeBarDemo.svelte') }),
    '/progress': wrap({ asyncComponent: () => import('./pages/progress/ProgressDemo.svelte') }),
    '/progressLoop': wrap({ asyncComponent: () => import('./pages/progressLoop/ProgressLoopDemo.svelte') }),
    '/mask': wrap({ asyncComponent: () => import('./pages/mask/MaskDemo.svelte') }),
    '/toast': wrap({ asyncComponent: () => import('./pages/toast/ToastDemo.svelte') }),
    '/loading': wrap({ asyncComponent: () => import('./pages/loading/LoadingDemo.svelte') }),
    '/popup': wrap({ asyncComponent: () => import('./pages/popup/PopupDemo.svelte') }),
    '/bottomSheet': wrap({ asyncComponent: () => import('./pages/bottomSheet/BottomSheetDemo.svelte') }),
    '/modal': wrap({ asyncComponent: () => import('./pages/modal/ModalDemo.svelte') }),
    '/dialog': wrap({ asyncComponent: () => import('./pages/dialog/DialogDemo.svelte') }),
    '/actionSheet': wrap({ asyncComponent: () => import('./pages/actionSheet/ActionSheetDemo.svelte') }),
    '/picker': wrap({ asyncComponent: () => import('./pages/picker/PickerDemo.svelte') }),
    '/asyncPicker': wrap({ asyncComponent: () => import('./pages/asyncPicker/AsyncPickerDemo.svelte') }),
    '/timePicker': wrap({ asyncComponent: () => import('./pages/timePicker/TimePickerDemo.svelte') }),
    '/calendar': wrap({ asyncComponent: () => import('./pages/calendar/CalendarDemo.svelte') }),
    '/pagination': wrap({ asyncComponent: () => import('./pages/pagination/PaginationDemo.svelte') }),
    '*': Home,
};
export const routes_en = {
    '/': Home,
    '/button': wrap({ asyncComponent: () => import('./pages/button/ButtonDemo_en.svelte') }),
    '/icon': wrap({ asyncComponent: () => import('./pages/icon/IconDemo_en.svelte') }),
    '/navBar': wrap({ asyncComponent: () => import('./pages/navBar/NavBarDemo_en.svelte') }),
    '/divider': wrap({ asyncComponent: () => import('./pages/divider/DividerDemo_en.svelte') }),
    '/cell': wrap({ asyncComponent: () => import('./pages/cell/CellDemo_en.svelte') }),
    '/switch': wrap({ asyncComponent: () => import('./pages/switch/SwitchDemo_en.svelte') }),
    '/avatar': wrap({ asyncComponent: () => import('./pages/avatar/AvatarDemo_en.svelte') }),
    '/tabs': wrap({ asyncComponent: () => import('./pages/tabs/TabsDemo_en.svelte') }),
    '/tabBar': wrap({ asyncComponent: () => import('./pages/tabBar/TabBarDemo_en.svelte') }),
    '/steps': wrap({ asyncComponent: () => import('./pages/steps/StepsDemo_en.svelte') }),
    '/indexBar': wrap({ asyncComponent: () => import('./pages/indexBar/IndexBarDemo_en.svelte') }),
    '/radio': wrap({ asyncComponent: () => import('./pages/radio/RadioDemo_en.svelte') }),
    '/checkbox': wrap({ asyncComponent: () => import('./pages/checkbox/CheckboxDemo_en.svelte') }),
    '/input': wrap({ asyncComponent: () => import('./pages/input/InputDemo_en.svelte') }),
    '/grids': wrap({ asyncComponent: () => import('./pages/grids/GridsDemo_en.svelte') }),
    '/swiper': wrap({ asyncComponent: () => import('./pages/swiper/SwiperDemo_en.svelte') }),
    '/placeholder': wrap({ asyncComponent: () => import('./pages/placeholder/PlaceholderDemo_en.svelte') }),
    '/skeleton': wrap({ asyncComponent: () => import('./pages/skeleton/SkeletonDemo_en.svelte') }),
    '/rate': wrap({ asyncComponent: () => import('./pages/rate/RateDemo_en.svelte') }),
    '/slider': wrap({ asyncComponent: () => import('./pages/slider/SliderDemo_en.svelte') }),
    '/badge': wrap({ asyncComponent: () => import('./pages/badge/BadgeDemo_en.svelte') }),
    '/noticeBar': wrap({ asyncComponent: () => import('./pages/noticeBar/NoticeBarDemo_en.svelte') }),
    '/progress': wrap({ asyncComponent: () => import('./pages/progress/ProgressDemo_en.svelte') }),
    '/progressLoop': wrap({ asyncComponent: () => import('./pages/progressLoop/ProgressLoopDemo_en.svelte') }),
    '/mask': wrap({ asyncComponent: () => import('./pages/mask/MaskDemo_en.svelte') }),
    '/toast': wrap({ asyncComponent: () => import('./pages/toast/ToastDemo_en.svelte') }),
    '/loading': wrap({ asyncComponent: () => import('./pages/loading/LoadingDemo_en.svelte') }),
    '/popup': wrap({ asyncComponent: () => import('./pages/popup/PopupDemo_en.svelte') }),
    '/bottomSheet': wrap({ asyncComponent: () => import('./pages/bottomSheet/BottomSheetDemo_en.svelte') }),
    '/modal': wrap({ asyncComponent: () => import('./pages/modal/ModalDemo_en.svelte') }),
    '/dialog': wrap({ asyncComponent: () => import('./pages/dialog/DialogDemo_en.svelte') }),
    '/actionSheet': wrap({ asyncComponent: () => import('./pages/actionSheet/ActionSheetDemo_en.svelte') }),
    '/picker': wrap({ asyncComponent: () => import('./pages/picker/PickerDemo_en.svelte') }),
    '/asyncPicker': wrap({ asyncComponent: () => import('./pages/asyncPicker/AsyncPickerDemo_en.svelte') }),
    '/timePicker': wrap({ asyncComponent: () => import('./pages/timePicker/TimePickerDemo_en.svelte') }),
    '/calendar': wrap({ asyncComponent: () => import('./pages/calendar/CalendarDemo_en.svelte') }),
    '/pagination': wrap({ asyncComponent: () => import('./pages/pagination/PaginationDemo_en.svelte') }),
    '*': Home,
};
