# 当分支 main 有 push 事件并且此次 push 包含了 packages/stdf/package.json 文件时，执行以下任务

name: PUBLISH STDF

on:
    push:
        branches:
            - mian
        paths:
            - 'packages/stdf/package.json'

jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: write

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js environment
              uses: actions/setup-node@v3
              with:
                  node-version: 20.x

            # 将 README.md 和 LICENSE 复制到 packages/stdf 目录下
            - name: Copy Files
              run: |
                  cp README.md packages/stdf/README.md
                  cp LICENSE packages/stdf/LICENSE

            # 打包 packages/rollup-plugin-stdf-icon 并构建
            - name: Build rollup-plugin-stdf-icon
              run: |
                  cd packages/rollup-plugin-stdf-icon
                  npm install
                  npm run build
                  cd ../../

            # cd packages/stdf 目录下
            # 发布 stdf 到 npm
            - name: Publish
              run: |
                  cd packages/stdf
                  npm install
                  npm run package
                  npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
                  npm publish --provenance
              env:
                  CI: true
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
