// 英语 english
export const en_US = {
    sort: 0,
    name: 'English',
    hnay: 'Has not adapted yet',
    pn: 'Please enter the project name',
    pncbne: 'Project name cannot be empty',
    pane: 'Project name already exists, please change it!',
    psat: 'Please select a template',
    oc: 'Operation cancelled',
    pca: 'Please choose again',
    psai: 'Please select icon usage',
    pstm: 'Please select theme mode',
    pm: 'Please select package manager',
    cfsing: 'Creating file...',
    pcsucc: 'Project created successfully!',
    tgs: 'To get started:',
    pcyt_vt: 'Tip: please configure Initial Color System in src/app.css, reference https://stdf.design/guide/theme',
    pcyt_vu: 'Tip: please configure Initial Color System in src/app.css, reference https://stdf.design/guide/theme',
    cferror: 'Failed to create file',
    pectn: 'Please enter the correct template name!',
    pic: 'Please enter the correct icon usage!',
    ptm: 'Please enter the correct theme mode!',
    tms: 'Initial theme (STDF), add custom themes later',
    tmm: '3 built-in themes',
    tma: 'All 42 built-in themes',
    iconSvgSymbolHint: 'Vite plugin for SVG symbol sprites (https://github.com/any-tdf/vite-plugin-svg-symbol)',
    iconIconifyHint: 'Use Iconify icon sets with Tailwind CSS (https://iconify.design)',
    iconBothHint: 'Use both SVG symbol sprites and Iconify',
    iconNoneHint: 'No icon solution, configure manually later',
    themeGeneratorHint: 'You can generate custom themes at https://stdf.design/guide/generator',
};

// 简体中文 chinese
export const zh_CN = {
    sort: 1,
    name: '简体中文',
    hnay: '暂未适配',
    pn: '请输入项目名称',
    pncbne: '项目名称不能为空',
    pane: '项目名称已存在，请换一个！',
    psat: '请选择一个模板',
    oc: '操作已取消',
    pca: '请重新选择',
    psai: '请选择图标使用方式',
    pstm: '请选择主题模式',
    pm: '请选择包管理工具',
    cfsing: '正在创建文件...',
    pcsucc: '项目创建成功！',
    tgs: '开始：',
    pcyt_vt: '提示：请到 src/app.css 配置初始主题色，参考 https://stdf.design/guide/theme',
    pcyt_vu: '提示：请到 src/app.css 配置初始主题色，参考 https://stdf.design/guide/theme',
    cferror: '创建文件失败',
    pectn: '请输入正确的模板名称！',
    pic: '请输入正确的图标使用方式！',
    ptm: '请输入正确的主题模式！',
    tms: '初始主题（STDF），后续可增加自定义主题',
    tmm: '内置 3 个主题',
    tma: '全部 42 个内置主题',
    iconSvgSymbolHint: 'SVG symbol 雪碧图 Vite 插件（https://github.com/any-tdf/vite-plugin-svg-symbol）',
    iconIconifyHint: '配合 Tailwind CSS 使用 Iconify 图标集（https://iconify.design）',
    iconBothHint: '同时使用 SVG symbol 雪碧图和 Iconify',
    iconNoneHint: '不用处理图标，或后续配置',
    themeGeneratorHint: '可到 https://stdf.design/guide/generator 配置生成自定义主题',
};

// 繁體中文 chinese traditional
export const zh_TW = {
    sort: 2,
    name: '繁體中文',
    hnay: '暫未適配',
    pn: '請輸入項目名稱',
    pncbne: '項目名稱不能為空',
    pane: '項目名稱已存在，請換一個！',
    psat: '請選擇一個模板',
    oc: '操作已取消',
    pca: '請重新選擇',
    psai: '請選擇圖標使用方式',
    pstm: '請選擇主題模式',
    pm: '請選擇包管理工具',
    cfsing: '正在創建文件...',
    pcsucc: '項目創建成功！',
    tgs: '開始：',
    pcyt_vt: '提示：請到 src/app.css 配置初始主題色，參考 https://stdf.design/guide/theme',
    pcyt_vu: '提示：請到 src/app.css 配置初始主題色，參考 https://stdf.design/guide/theme',
    cferror: '創建文件失敗',
    pectn: '請輸入正確的模板名稱！',
    pic: '請輸入正確的圖標使用方式！',
    ptm: '請輸入正確的主題模式！',
    tms: '初始主題（STDF），後續可增加自定義主題',
    tmm: '內置 3 個主題',
    tma: '全部 42 個內置主題',
    iconSvgSymbolHint: 'SVG symbol 雪碧圖 Vite 插件（https://github.com/any-tdf/vite-plugin-svg-symbol）',
    iconIconifyHint: '配合 Tailwind CSS 使用 Iconify 圖標集（https://iconify.design）',
    iconBothHint: '同時使用 SVG symbol 雪碧圖和 Iconify',
    iconNoneHint: '不使用圖標方案，稍後手動配置',
    themeGeneratorHint: '可到 https://stdf.design/guide/generator 配置生成自定義主題',
};

// 日语 japanese
export const ja_JP = {
    sort: 3,
    name: '日本語',
    hnay: 'まだ適応されていません',
    pn: 'プロジェクト名を入力してください',
    pncbne: 'プロジェクト名は空にできません',
    pane: 'プロジェクト名が既に存在します，別の名前を入力してください！',
    psat: 'テンプレートを選択してください',
    oc: '操作がキャンセルされました',
    pca: 'もう一度選択してください',
    psai: 'アイコンの使用方法を選択してください',
    pstm: 'Please select theme mode',
    pm: 'パッケージマネージャーを選択してください',
    cfsing: 'ファイルを作成しています...',
    pcsucc: 'プロジェクトが正常に作成されました！',
    tgs: '開始：',
    pcyt_vt: 'ヒント：src/app.css ファイルで初期カラーシステムを設定し、参考 https://stdf.design/guide/theme',
    pcyt_vu: 'ヒント：src/app.css ファイルで初期カラーシステムを設定し、参考 https://stdf.design/guide/theme',
    cferror: 'ファイルの作成に失敗しました',
    pectn: '正しいテンプレート名を入力してください！',
    pic: '正しいアイコン使用方法を入力してください！',
    ptm: 'Please enter the correct theme mode!',
    tms: 'Initial theme (STDF), add custom themes later',
    tmm: '3 built-in themes',
    tma: 'All 42 built-in themes',
    iconSvgSymbolHint: 'SVG シンボルスプライト用 Vite プラグイン（https://github.com/any-tdf/vite-plugin-svg-symbol）',
    iconIconifyHint: 'Tailwind CSS で Iconify アイコンセットを使用（https://iconify.design）',
    iconBothHint: 'SVG シンボルスプライトと Iconify の両方を使用',
    iconNoneHint: 'アイコンソリューションなし、後で手動設定',
    themeGeneratorHint: 'https://stdf.design/guide/generator でカスタムテーマを生成できます',
};

// 韩语 korean
export const ko_KR = {
    sort: 4,
    name: '한국어',
    hnay: '아직 적응하지 못했습니다',
    pn: '프로젝트 이름을 입력하십시오',
    pncbne: '프로젝트 이름은 비워 둘 수 없습니다',
    pane: '프로젝트 이름이 이미 있습니다，다른 이름을 입력하십시오！',
    psat: '템플릿을 선택하십시오',
    oc: '작업이 취소되었습니다',
    pca: '다시 선택하십시오',
    psai: '아이콘 사용 방법을 선택하십시오',
    pstm: 'Please select theme mode',
    pm: '패키지 관리자를 선택하십시오',
    cfsing: '파일을 만드는 중입니다...',
    pcsucc: '프로젝트가 성공적으로 생성되었습니다！',
    tgs: '시작：',
    pcyt_vt: '팁: src/app.css 파일에서 초기 색상 시스템을 구성하고 참조 https://stdf.design/guide/theme',
    pcyt_vu: '팁: src/app.css 파일에서 초기 색상 시스템을 구성하고 참조 https://stdf.design/guide/theme',
    cferror: '파일 생성 실패',
    pectn: '올바른 템플릿 이름을 입력하십시오!',
    pic: '올바른 아이콘 사용 방법을 입력하십시오!',
    ptm: 'Please enter the correct theme mode!',
    tms: 'Initial theme (STDF), add custom themes later',
    tmm: '3 built-in themes',
    tma: 'All 42 built-in themes',
    iconSvgSymbolHint: 'SVG 심볼 스프라이트용 Vite 플러그인 (https://github.com/any-tdf/vite-plugin-svg-symbol)',
    iconIconifyHint: 'Tailwind CSS 와 함께 Iconify 아이콘 세트 사용 (https://iconify.design)',
    iconBothHint: 'SVG 심볼 스프라이트와 Iconify 모두 사용',
    iconNoneHint: '아이콘 솔루션 없음, 나중에 수동 구성',
    themeGeneratorHint: 'https://stdf.design/guide/generator 에서 사용자 정의 테마를 생성할 수 있습니다',
};

// 西班牙语 spanish
export const es_ES = {
    sort: 5,
    name: 'Español',
    hnay: 'Aún no se ha adaptado',
    pn: 'Por favor ingrese el nombre del proyecto',
    pncbne: 'El nombre del proyecto no puede estar vacío',
    pane: 'El nombre del proyecto ya existe, por favor ingrese otro nombre!',
    psat: 'Por favor seleccione una plantilla',
    oc: 'Operación cancelada',
    pca: 'Por favor, elija de nuevo',
    psai: 'Por favor seleccione el uso de iconos',
    pstm: 'Please select theme mode',
    pm: 'Por favor seleccione un administrador de paquetes',
    cfsing: 'Creando archivo...',
    pcsucc: 'Proyecto creado con éxito!',
    tgs: 'Para empezar:',
    pcyt_vt: 'Consejo: configure su sistema de colores en reference https://stdf.design/guide/theme',
    pcyt_vu: 'Consejo: configure su sistema de colores en reference https://stdf.design/guide/theme',
    cferror: 'Error al crear archivo',
    pectn: '¡Por favor ingrese el nombre de la plantilla correcto!',
    pic: '¡Por favor ingrese el uso correcto de iconos!',
    ptm: 'Please enter the correct theme mode!',
    tms: 'Initial theme (STDF), add custom themes later',
    tmm: '3 built-in themes',
    tma: 'All 42 built-in themes',
    iconSvgSymbolHint: 'Plugin Vite para sprites de símbolos SVG (https://github.com/any-tdf/vite-plugin-svg-symbol)',
    iconIconifyHint: 'Usar conjuntos de iconos Iconify con Tailwind CSS (https://iconify.design)',
    iconBothHint: 'Usar tanto sprites de símbolos SVG como Iconify',
    iconNoneHint: 'Sin solución de iconos, configurar manualmente después',
    themeGeneratorHint: 'Puede generar temas personalizados en https://stdf.design/guide/generator',
};

// 俄语 russian
export const ru_RU = {
    sort: 6,
    name: 'Русский',
    hnay: 'Еще не адаптировано',
    pn: 'Пожалуйста, введите название проекта',
    pncbne: 'Название проекта не может быть пустым',
    pane: 'Название проекта уже существует, пожалуйста, введите другое название!',
    psat: 'Пожалуйста, выберите шаблон',
    oc: 'Операция отменена',
    pca: 'Пожалуйста, выберите снова',
    psai: 'Пожалуйста, выберите использование иконок',
    pstm: 'Please select theme mode',
    pm: 'Пожалуйста, выберите пакетный менеджер',
    cfsing: 'Создание файла...',
    pcsucc: 'Проект успешно создан!',
    tgs: 'Чтобы начать:',
    pcyt_vt: 'Совет: настройте свой цветовой систему в ссылке https://stdf.design/guide/theme',
    pcyt_vu: 'Совет: настройте свой цветовой систему в ссылке https://stdf.design/guide/theme',
    cferror: 'Не удалось создать файл',
    pectn: 'Пожалуйста, введите правильное название шаблона!',
    pic: 'Пожалуйста, введите правильное использование иконок!',
    ptm: 'Please enter the correct theme mode!',
    tms: 'Initial theme (STDF), add custom themes later',
    tmm: '3 built-in themes',
    tma: 'All 42 built-in themes',
    iconSvgSymbolHint: 'Плагин Vite для SVG символьных спрайтов (https://github.com/any-tdf/vite-plugin-svg-symbol)',
    iconIconifyHint: 'Использовать наборы иконок Iconify с Tailwind CSS (https://iconify.design)',
    iconBothHint: 'Использовать как SVG символьные спрайты, так и Iconify',
    iconNoneHint: 'Без решения для иконок, настроить вручную позже',
    themeGeneratorHint: 'Вы можете создать пользовательские темы на https://stdf.design/guide/generator',
};

// 法语 french
export const fr_FR = {
    sort: 7,
    name: 'Français',
    hnay: "N'a pas encore adapté",
    pn: 'Veuillez saisir le nom du projet',
    pncbne: 'Le nom du projet ne peut pas être vide',
    pane: 'Le nom du projet existe déjà, veuillez entrer un autre nom!',
    psat: 'Veuillez sélectionner un modèle',
    oc: 'Opération annulée',
    pca: 'Veuillez choisir à nouveau',
    psai: "Veuillez sélectionner le mode d'utilisation des icônes",
    pstm: 'Please select theme mode',
    pm: 'Veuillez sélectionner un gestionnaire de paquets',
    cfsing: 'Création de fichier...',
    pcsucc: 'Projet créé avec succès!',
    tgs: 'Pour commencer:',
    pcyt_vt: 'Conseil: veuillez configurer votre système de couleurs dans reference https://stdf.design/guide/theme',
    pcyt_vu: 'Conseil: veuillez configurer votre système de couleurs dans reference https://stdf.design/guide/theme',
    cferror: 'Échec de la création du fichier',
    pectn: 'Veuillez saisir le nom du modèle correct!',
    pic: "Veuillez saisir le mode d'utilisation correct des icônes!",
    ptm: 'Please enter the correct theme mode!',
    tms: 'Initial theme (STDF), add custom themes later',
    tmm: '3 built-in themes',
    tma: 'All 42 built-in themes',
    iconSvgSymbolHint: 'Plugin Vite pour les sprites de symboles SVG (https://github.com/any-tdf/vite-plugin-svg-symbol)',
    iconIconifyHint: "Utiliser les ensembles d'icônes Iconify avec Tailwind CSS (https://iconify.design)",
    iconBothHint: 'Utiliser à la fois les sprites de symboles SVG et Iconify',
    iconNoneHint: "Pas de solution d'icônes, configurer manuellement plus tard",
    themeGeneratorHint: 'Vous pouvez générer des thèmes personnalisés sur https://stdf.design/guide/generator',
};

// 德语 german
export const de_DE = {
    sort: 8,
    name: 'Deutsch',
    hnay: 'Noch nicht angepasst',
    pn: 'Bitte geben Sie den Projektnamen ein',
    pncbne: 'Projektname darf nicht leer sein',
    pane: 'Projektname existiert bereits, bitte geben Sie einen anderen Namen ein!',
    psat: 'Bitte wählen Sie eine Vorlage aus',
    oc: 'Vorgang abgebrochen',
    pca: 'Bitte wählen Sie erneut',
    psai: 'Bitte wählen Sie die Verwendung von Icons',
    pstm: 'Please select theme mode',
    pm: 'Bitte wählen Sie einen Paketmanager aus',
    cfsing: 'Erstelle Datei...',
    pcsucc: 'Projekt erfolgreich erstellt!',
    tgs: 'Um zu beginnen:',
    pcyt_vt: 'Tip: please configure your color system in reference https://stdf.design/guide/theme',
    pcyt_vu: 'Tip: please configure your color system in reference https://stdf.design/guide/theme',
    cferror: 'Fehler beim Erstellen der Datei',
    pectn: 'Bitte geben Sie den richtigen Vorlagennamen ein!',
    pic: 'Bitte geben Sie den richtigen Verwendungsmodus für Icons ein!',
    ptm: 'Please enter the correct theme mode!',
    tms: 'Initial theme (STDF), add custom themes later',
    tmm: '3 built-in themes',
    tma: 'All 42 built-in themes',
    iconSvgSymbolHint: 'Vite-Plugin für SVG-Symbol-Sprites (https://github.com/any-tdf/vite-plugin-svg-symbol)',
    iconIconifyHint: 'Iconify-Icon-Sets mit Tailwind CSS verwenden (https://iconify.design)',
    iconBothHint: 'Sowohl SVG-Symbol-Sprites als auch Iconify verwenden',
    iconNoneHint: 'Keine Icon-Lösung, später manuell konfigurieren',
    themeGeneratorHint: 'Sie können benutzerdefinierte Themen unter https://stdf.design/guide/generator erstellen',
};

// 意大利语 italian
export const it_IT = {
    sort: 9,
    name: 'Italiano',
    hnay: 'Non ancora adattato',
    pn: 'Inserisci il nome del progetto',
    pncbne: 'Il nome del progetto non può essere vuoto',
    pane: 'Il nome del progetto esiste già, inserisci un altro nome!',
    psat: 'Seleziona un modello',
    oc: 'Operazione annullata',
    pca: 'Seleziona di nuovo',
    psai: 'Seleziona il modo di utilizzo delle icone',
    pstm: 'Please select theme mode',
    pm: 'Seleziona un gestore di pacchetti',
    cfsing: 'Creazione del file in corso...',
    pcsucc: 'Progetto creato con successo!',
    tgs: 'Per iniziare:',
    pcyt_vt: 'Consiglio: configura il tuo sistema di colori in https://stdf.design/guide/theme',
    pcyt_vu: 'Consiglio: configura il tuo sistema di colori in https://stdf.design/guide/theme',
    cferror: 'Impossibile creare il file',
    pectn: 'Inserisci il nome del modello corretto!',
    pic: 'Inserisci il modo di utilizzo corretto delle icone!',
    ptm: 'Please enter the correct theme mode!',
    tms: 'Initial theme (STDF), add custom themes later',
    tmm: '3 built-in themes',
    tma: 'All 42 built-in themes',
    iconSvgSymbolHint: 'Plugin Vite per sprite di simboli SVG (https://github.com/any-tdf/vite-plugin-svg-symbol)',
    iconIconifyHint: 'Usa set di icone Iconify con Tailwind CSS (https://iconify.design)',
    iconBothHint: 'Usa sia sprite di simboli SVG che Iconify',
    iconNoneHint: 'Nessuna soluzione per icone, configurare manualmente in seguito',
    themeGeneratorHint: 'Puoi generare temi personalizzati su https://stdf.design/guide/generator',
};
